In [ ]:
#What is Pandas?
#Python library used for working with structured
#data sets(tables). It has functions for
#exploring and manipulating data. Similar to data table
#in sql and excel
import pandas as pd
pd.__version__

'2.2.3'

In [ ]:
#What is Dataframe?
#It's a structured data constructed with rows and columns,
#similar to a SQL tables or Excel tables
import pandas as pd
df=pd.DataFrame([1,2,3],columns=['roll'])
print(df)
print(type(df))

   roll
0     1
1     2
2     3
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#using dictionary of lists
data={
    'Name':['Madhav','Vishakha','Lalita','Sayantan'],
    'Age':[16,17,18,36],
    'Salary':[55000,25000,35000,75000]
}
df=pd.DataFrame(data)
print(df)
#print top 2 rows
df.head(2)
#print last 2 rows
df.tail(2)
#shape---return a tuple contains following row & column
df.shape
df.info() #info method prints information about the DataFrame
df.describe() ## describe method generates descriptive statistics of DataFrame, only for numerical-value columns

       Name  Age  Salary
0    Madhav   16   55000
1  Vishakha   17   25000
2    Lalita   18   35000
3  Sayantan   36   75000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

             Age        Salary
count   4.000000      4.000000
mean   21.750000  47500.000000
std     9.535023  22173.557826
min    16.000000  25000.000000
25%    16.750000  32500.000000
50%    17.500000  45000.000000
75%    22.500000  60000.000000
max    36.000000  75000.000000

In [ ]:
df.to_csv('Test_data.csv',index=False)# save file- export data frame

In [ ]:
load_df=pd.read_csv('Test_data.csv') #load file-import dataframe
load_df

       Name  Age  Salary
0    Madhav   16   55000
1  Vishakha   17   25000
2    Lalita   18   35000
3  Sayantan   36   75000

In [ ]:
df['Name']

0      Madhav
1    Vishakha
2      Lalita
3    Sayantan
Name: Name, dtype: object

In [ ]:
# select multiple columns
df[['Name', 'Salary']]

       Name  Salary
0    Madhav   55000
1  Vishakha   25000
2    Lalita   35000
3  Sayantan   75000

In [ ]:
# select single row || loc - label based index
df.loc[df.Name=='Madhav']

     Name  Age  Salary
0  Madhav   16   55000

In [ ]:
# select multiple rows || loc - label based index
df.loc[(df.Name=='Madhav') & (df.Salary>=50000)]

     Name  Age  Salary
0  Madhav   16   55000

In [ ]:
df.loc[0:2]

       Name  Age  Salary
0    Madhav   16   55000
1  Vishakha   17   25000
2    Lalita   18   35000

In [ ]:
# Select Rows || iloc - index-value based

df.iloc[0:4:1] # [start:stop:step]

       Name  Age  Salary
0    Madhav   16   55000
1  Vishakha   17   25000
2    Lalita   18   35000
3  Sayantan   36   75000

In [ ]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable
df_age_filter

       Name  Age  Salary
2    Lalita   18   35000
3  Sayantan   36   75000

In [ ]:
df[(df['Age'] >= 18) & (df['Salary'] >= 50000)] # multiple filter conditions

       Name  Age  Salary
3  Sayantan   36   75000

In [ ]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2        Lalita            18         35000
3      Sayantan            36         75000

In [ ]:
# Create a new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  Age  Salary Team
0    Madhav   16   55000  CEO
1  Vishakha   17   25000   HR
2    Lalita   18   35000  CTO
3  Sayantan   36   75000   DA

In [ ]:
# Add new columns using existing column/s
df['Bonus'] = df['Salary'] * 0.20
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   55000  CEO  11000.0
1  Vishakha   17   25000   HR   5000.0
2    Lalita   18   35000  CTO   7000.0
3  Sayantan   36   75000   DA  15000.0

In [ ]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   55000  CEO  11000.0
1  Vishakha   17   25000   HR   5000.0
2    Lalita   18   35000  CTO   7000.0
3  Sayantan   36   75000   DA  15000.0
4       ABC   21   21000   IT   2000.0
5       ABC   21   21000   IT   2000.0

In [ ]:
# Add new row - at the end of dataframe
df.loc[3] = ['xyz', 21, 21000, 'IT', 2000]
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   95000  CEO  11000.0
1  Vishakha   17   25000   HR   5000.0
2    Lalita   18   35000  CTO   7000.0
3       xyz   21   21000   IT   2000.0
4       ABC   21   21000   IT   2000.0
5       ABC   21   21000   IT   2000.0

In [ ]:
import numpy as np
import pandas as pd

# Example DataFrame
df = pd.DataFrame(
    {
        "Name": ["XYZ", "LMN", "OPQ"],
        "Age":21,
        "Salary":25000,
        "Dept": ["HR", "Finance", "Sales"],
        "Bonus":4000,
    }
)





#print(df)
# New row data
new_row = ["ABC", 21, 21000, "IT", 2000]
df_new = pd.DataFrame(np.insert(df.values, 2, values=new_row, axis=0), columns=df.columns)
print(df)
print(df_new)

  Name  Age  Salary     Dept  Bonus
0  XYZ   21   25000       HR   4000
1  LMN   21   25000  Finance   4000
2  OPQ   21   25000    Sales   4000
  Name Age Salary     Dept Bonus
0  XYZ  21  25000       HR  4000
1  LMN  21  25000  Finance  4000
2  ABC  21  21000       IT  2000
3  OPQ  21  25000    Sales  4000

In [ ]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'ABC'].index) # delete row, axis= 0
df

  Name  Age  Salary     Dept  Bonus
0  XYZ   21   25000       HR   4000
1  LMN   21   25000  Finance   4000
2  OPQ   21   25000    Sales   4000

In [ ]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Name') #ascending order, by default

  Name  Age  Salary     Dept  Bonus
1  LMN   21   25000  Finance   4000
2  OPQ   21   25000    Sales   4000
0  XYZ   21   25000       HR   4000

In [ ]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28']
df

  Name  Age  Salary     Dept  Bonus         DOJ
0  XYZ   21   25000       HR   4000  2024-01-01
1  LMN   21   25000  Finance   4000  2024-01-15
2  OPQ   21   25000    Sales   4000  2024-03-28

In [ ]:
df['DOJ'] = pd.to_datetime(df['DOJ']) # change to date-time type

In [ ]:
df['DOJ'].dtype # date-time type

dtype('<M8[ns]')

In [ ]:
df['DOJ'].dt.year  #doj year

0    2024
1    2024
2    2024
Name: DOJ, dtype: int32

In [ ]:
df.isnull() #  Detect missing values

    Name    Age  Salary   Dept  Bonus    DOJ
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False

In [ ]:
import numpy as np  # to create null values below

In [ ]:
df.loc[df.Name=='XYZ', 'Salary'] = np.nan # adding a null value

In [ ]:
df.isnull()

    Name    Age  Salary   Dept  Bonus    DOJ
0  False  False    True  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False

In [ ]:
df.isnull().sum() # count of null values by columns

Name      0
Age       0
Salary    1
Dept      0
Bonus     0
DOJ       0
dtype: int64

In [ ]:
df.fillna(0) # fill null values with 0

  Name  Age   Salary     Dept  Bonus        DOJ
0  XYZ   21      0.0       HR   4000 2024-01-01
1  LMN   21  25000.0  Finance   4000 2024-01-15
2  OPQ   21  25000.0    Sales   4000 2024-03-28

In [ ]:
# update value in dataframe using index-name
df.loc[0, 'Salary'] = 95000
df

       Name  Age  Salary Team    Bonus
0    Madhav   16   95000  CEO  11000.0
1  Vishakha   17   25000   HR   5000.0
2    Lalita   18   35000  CTO   7000.0
3  Sayantan   36   75000   DA  15000.0
4       ABC   21   21000   IT   2000.0
5       ABC   21   21000   IT   2000.0